### ISSUE TITLE
Noise at Scale > 0

### ISSUE THREAD

**Issue by Dariensg** [Mawiszus/World-GAN#4]
Hi,

I'm currently working on an undergraduate Honors thesis building upon the work that you've done, but have been having some issues and was wondering if you might be able to clarify part of this code. I have found that when training the GAN on my own area, the generated area seems to always be nearly identical to the original. I've done some exploration of the code and found that [this](https://github.com/Mawiszus/World-GAN/blob/6e09278c5cef5d40f4faae37e22f92899c88113f/train_single_scale.py#L92) line seems to imply that there is no noise being applied at other scales, despite the comment saying that noise should be added to the previous output. Could you please clarify how noise is handled at scales > 0? The fact that this appears to be no noise at other scales would explain why my generated worlds are nearly identical to the original, but I'm not confident in how I can modify this to get much more variation. Thank you for your help!

**Comment by Dariensg** [comment]
After some more investigation, I've discovered the usage of the alpha and lambda_grad config parameters and how they play into the noise. I was curious if there was a reason that the 100 and 0.1 values were chosen as defaults respectively? Were there optimal values for these parameters found in your research that led to the greatest variation in generated samples while still maintaining some semblance of the original world sections?

**Comment by Mawiszus** [comment]
Hi Dariensg,

glad you found out about the correct parameters on your own. 
As to the default values, you are correct, these are empirically chosen values that worked best with our goal of keeping the original structure mostly intact.
Keeping the noise for the higher scales small is something that has worked well since the original [SinGAN](https://github.com/tamarott/SinGAN), which our work was based on.

If you are interested:
For the 2D Method TOAD-GAN, we created a [GUI](https://github.com/Mawiszus/TOAD-GUI) which allows you to resample the noise maps at the different scales, so you can see a live representation of the difference these noise maps make on a generated Mario Level.

Do you have further questions?

Kind Regards,
Maren

**Comment by Dariensg** [comment]
Hi Maren,

Thank you for the quick response! I'm currently working on trying to get the World-GAN model to learn a chunk of the world consisting of multiple "biomes." What I've found, however, is that the generated section is nearly exactly the input section. I've also noticed that the generated samples seem to always be the same, despite the random seeds varying.

After discovering the parameters, I've tried adjusting them to drastic numbers to see if it would have an effect. So far, I've tried dropping alpha to 0 and increasing lambda_grad to 0.75. Neither of these seemed to change the output of the model, interestingly.

Do you have any ideas as to what may be causing the generated chunks to not have any significant variance? Based on your paper, I was under the impression that the generated sections had great variability in what was generated. It currently seems to be functioning for me more as a fairly effective autoencoder, rather than generating a unique section of a world. Is there a required minimum size of the world or minimum iterations per scale? I've tried adjusting the iterations with no luck in output difference.

Thank you again for your quick response! I appreciate how you are so willing to address questions!

Sincerely,
Darien

**Comment by Dariensg** [comment]
Thank you so much for your quick response! That's all for now, but thank you so much for your help! I had some accidental bugs I introduced into my sample generation when adapting your work, but I figured that out and was able to see the results I expected! I'll let you know if I have any more issues!
