### ISSUE TITLE
Pickle Error When Training Block2Vec Embedding

### ISSUE THREAD

**Issue by Dariensg** [Mawiszus/World-GAN#5]
Hi again!

I've made a lot of progress, but I'm having an error when trying to train a block2vec embedding using your existing code. I'm getting the error: `AttributeError: Can't pickle local object 'create_compund_nbt_class.<locals>.CompundNBTTag'`, which I've been able to trace as a result of the CompoundNBTTag class being declared locally within PyAnvilEditor.

I was curious how you got around this error. I've tried using the exact same PyTorch and PyTorchLightning versions that you have in the requirements, but there has been no change. I've learned that this error comes from PyTorch Lightning trying to use multiprocessing for the training, but have yet to find a way around the error.

Any help would be appreciated! Thank you!

**Comment by Mawiszus** [comment]
Hi Darien,

since you have marked the issue as solved, I hope you found a solution. 
It has been a while since I have worked on this project and I do not remember this being an issue. If it is resolved already I will not look further into it.

Kind regards,
Maren

**Comment by Dariensg** [comment]
Hi Maren,

Thanks again! I did actually resolve this by setting the __qualname__ in the classes before returning them from their respective functions, a solution that I can foresee being useful for other projects in the future!

Sincerely,
Darien
